import type {
  Order,
  Customer,
  AttentionCase,
  WhatsAppConversation,
  CourierIntegration,
  AutomationRule,
  TeamMember,
  DashboardMetrics,
} from "./types";

// ============================================================
// DASHBOARD METRICS
// ============================================================
export const dashboardMetrics: DashboardMetrics = {
  inTransit: 100,
  delivered: 2356,
  deliveryRate: 79,
  inYourBank: 8200000,
  courierOwes: 0,
  shippingCost: 412500,
  taxWithheld: 128000,
  todaysOrders: 84,
  pendingConfirmation: 23,
  confirmed: 41,
  rto: 153,
  rtoRate: 6.5,
  codCollected: 8475000,
  courierPayable: 384000,
  courierReceivable: 0,
  avgDeliveryTime: 2.4,
};

// 14-day delivery trend for charts
export const deliveryTrend = [
  { day: "Sep 17", delivered: 142, returned: 12, dispatched: 168 },
  { day: "Sep 18", delivered: 156, returned: 9, dispatched: 178 },
  { day: "Sep 19", delivered: 138, returned: 15, dispatched: 161 },
  { day: "Sep 20", delivered: 171, returned: 11, dispatched: 192 },
  { day: "Sep 21", delivered: 165, returned: 14, dispatched: 184 },
  { day: "Sep 22", delivered: 149, returned: 18, dispatched: 172 },
  { day: "Sep 23", delivered: 188, returned: 10, dispatched: 205 },
  { day: "Sep 24", delivered: 174, returned: 13, dispatched: 196 },
  { day: "Sep 25", delivered: 162, returned: 16, dispatched: 185 },
  { day: "Sep 26", delivered: 195, returned: 8, dispatched: 214 },
  { day: "Sep 27", delivered: 181, returned: 11, dispatched: 201 },
  { day: "Sep 28", delivered: 168, returned: 14, dispatched: 189 },
  { day: "Sep 29", delivered: 203, returned: 9, dispatched: 224 },
  { day: "Sep 30", delivered: 187, returned: 12, dispatched: 208 },
];

// Courier performance breakdown
export const courierPerformance = [
  { courier: "TCS", delivered: 842, returned: 68, deliveryRate: 92.5, cost: 186000 },
  { courier: "Leopards", delivered: 614, returned: 71, deliveryRate: 89.6, cost: 142000 },
  { courier: "Trax", delivered: 388, returned: 41, deliveryRate: 90.5, cost: 84000 },
  { courier: "M&P", delivered: 296, returned: 38, deliveryRate: 88.6, cost: 71 },
  { courier: "PostEx", delivered: 216, returned: 35, deliveryRate: 86.1, cost: 52 },
];

// City-wise distribution
export const cityDistribution = [
  { city: "Karachi", orders: 842, percentage: 35.8 },
  { city: "Lahore", orders: 614, percentage: 26.1 },
  { city: "Islamabad", orders: 286, percentage: 12.2 },
  { city: "Rawalpindi", orders: 168, percentage: 7.1 },
  { city: "Faisalabad", orders: 142, percentage: 6.0 },
  { city: "Multan", orders: 98, percentage: 4.2 },
  { city: "Peshawar", orders: 76, percentage: 3.2 },
  { city: "Others", orders: 124, percentage: 5.4 },
];

// ============================================================
// CUSTOMERS
// ============================================================
export const customers: Customer[] = [
  {
    id: "cus_001",
    firstName: "Ayesha",
    lastName: "Khan",
    phone: "0301-2345678",
    email: "ayesha.khan@email.com",
    city: "Lahore",
    address: "House 23, Block C, Gulberg III, Lahore",
    totalOrders: 12,
    deliveredOrders: 9,
    returnedOrders: 3,
    riskScore: 25,
    riskLevel: "LOW",
    lastOrderAmount: 4500,
    joinedAt: "2024-03-15",
  },
  {
    id: "cus_002",
    firstName: "Bilal",
    lastName: "Ahmed",
    phone: "0321-9876543",
    email: "bilal.ahmed@email.com",
    city: "Karachi",
    address: "Flat 4B, Al-Habib Apartments, Tariq Road, Karachi",
    totalOrders: 5,
    deliveredOrders: 5,
    returnedOrders: 0,
    riskScore: 8,
    riskLevel: "LOW",
    lastOrderAmount: 6200,
    joinedAt: "2024-06-22",
  },
  {
    id: "cus_003",
    firstName: "Sana",
    lastName: "Tariq",
    phone: "0333-4567890",
    city: "Multan",
    address: "Street 7, Cantt, Multan",
    totalOrders: 8,
    deliveredOrders: 4,
    returnedOrders: 4,
    riskScore: 72,
    riskLevel: "HIGH",
    lastOrderAmount: 3800,
    joinedAt: "2024-01-08",
  },
  {
    id: "cus_004",
    firstName: "Hira",
    lastName: "Saleem",
    phone: "0345-1122334",
    city: "Islamabad",
    address: "Plot 12, Street 9, F-8/3, Islamabad",
    totalOrders: 3,
    deliveredOrders: 2,
    returnedOrders: 1,
    riskScore: 45,
    riskLevel: "MEDIUM",
    lastOrderAmount: 8900,
    joinedAt: "2024-08-30",
  },
  {
    id: "cus_005",
    firstName: "Usman",
    lastName: "Raza",
    phone: "0300-5566778",
    email: "usman.raza@email.com",
    city: "Faisalabad",
    address: "House 156, Peoples Colony No. 2, Faisalabad",
    totalOrders: 15,
    deliveredOrders: 13,
    returnedOrders: 2,
    riskScore: 18,
    riskLevel: "LOW",
    lastOrderAmount: 12500,
    joinedAt: "2023-11-12",
  },
  {
    id: "cus_006",
    firstName: "Maham",
    lastName: "Ali",
    phone: "0312-8899001",
    city: "Rawalpindi",
    address: "Flat 7, Saddar Plaza, Saddar, Rawalpindi",
    totalOrders: 6,
    deliveredOrders: 3,
    returnedOrders: 3,
    riskScore: 68,
    riskLevel: "HIGH",
    lastOrderAmount: 5400,
    joinedAt: "2024-05-04",
  },
  {
    id: "cus_007",
    firstName: "Fatima",
    lastName: "Noor",
    phone: "0322-3344556",
    city: "Peshawar",
    address: "University Town, Peshawar",
    totalOrders: 9,
    deliveredOrders: 8,
    returnedOrders: 1,
    riskScore: 12,
    riskLevel: "LOW",
    lastOrderAmount: 3200,
    joinedAt: "2024-02-19",
  },
  {
    id: "cus_008",
    firstName: "Kamran",
    lastName: "Sheikh",
    phone: "0346-7788990",
    city: "Karachi",
    address: "Bungalow 89, DHA Phase 6, Karachi",
    totalOrders: 22,
    deliveredOrders: 21,
    returnedOrders: 1,
    riskScore: 5,
    riskLevel: "LOW",
    lastOrderAmount: 18900,
    joinedAt: "2023-07-22",
  },
];

// ============================================================
// ORDERS — full lifecycle
// ============================================================
export const orders: Order[] = [
  // ---------- UNCONFIRMED ----------
  {
    id: "ord_1043",
    orderNumber: "#1043",
    customerId: "cus_001",
    customerName: "Ayesha Khan",
    customerPhone: "0301-2345678",
    city: "Lahore",
    address: "House 23, Block C, Gulberg III, Lahore",
    items: [
      { id: "i1", productId: "p1", title: "Cotton Unstitched Suit (3 Piece)", sku: "COT-3PC-RED", quantity: 1, unitPrice: 4500, totalPrice: 4500 },
    ],
    codAmount: 4500,
    shippingFee: 180,
    totalAmount: 4500,
    isCod: true,
    status: "UNCONFIRMED",
    riskScore: 25,
    riskLevel: "LOW",
    confirmationMethod: "AUTO_CALL",
    createdAt: "2026-10-01T08:23:00",
    recommendedAction: "Customer answered auto-call and pressed 1. Auto-confirm in 30 minutes if no dispute.",
  },
  {
    id: "ord_1044",
    orderNumber: "#1044",
    customerId: "cus_002",
    customerName: "Bilal Ahmed",
    customerPhone: "0321-9876543",
    city: "Karachi",
    address: "Flat 4B, Al-Habib Apartments, Tariq Road, Karachi",
    items: [
      { id: "i2", productId: "p2", title: "Men's Casual Kameez Shalwar", sku: "MEN-CS-WHT", quantity: 2, unitPrice: 2400, totalPrice: 4800 },
      { id: "i3", productId: "p3", title: "Leather Sandals", sku: "LTH-SND-42", quantity: 1, unitPrice: 1400, totalPrice: 1400 },
    ],
    codAmount: 6200,
    shippingFee: 200,
    totalAmount: 6200,
    isCod: true,
    status: "UNCONFIRMED",
    riskScore: 8,
    riskLevel: "LOW",
    confirmationMethod: "WHATSAPP",
    createdAt: "2026-10-01T08:47:00",
    recommendedAction: "Low-risk repeat customer (5/5 delivered). Send WhatsApp confirmation template.",
  },
  {
    id: "ord_1045",
    orderNumber: "#1045",
    customerId: "cus_003",
    customerName: "Sana Tariq",
    customerPhone: "0333-4567890",
    city: "Multan",
    address: "Street 7, Cantt, Multan",
    items: [
      { id: "i4", productId: "p4", title: "Lawn Printed Suit (Summer Collection)", sku: "LWN-PRT-GRN", quantity: 1, unitPrice: 3800, totalPrice: 3800 },
    ],
    codAmount: 3800,
    shippingFee: 220,
    totalAmount: 3800,
    isCod: true,
    status: "UNCONFIRMED",
    riskScore: 72,
    riskLevel: "HIGH",
    riskReasons: ["Previous RTO history (4 returns)", "Customer hasn't replied to last 2 WhatsApp messages", "Address incomplete — no house number"],
    createdAt: "2026-10-01T09:12:00",
    recommendedAction: "HIGH RISK — verify customer by phone call before dispatch. Consider advance payment option.",
  },
  {
    id: "ord_1046",
    orderNumber: "#1046",
    customerId: "cus_009",
    customerName: "Zainab Iqbal",
    customerPhone: "0308-4455667",
    city: "Lahore",
    address: "House 78, Johar Town Block H, Lahore",
    items: [
      { id: "i5", productId: "p5", title: "Women's Khussa (Embellished)", sku: "WMN-KHS-38", quantity: 1, unitPrice: 2200, totalPrice: 2200 },
    ],
    codAmount: 2200,
    shippingFee: 150,
    totalAmount: 2200,
    isCod: true,
    status: "UNCONFIRMED",
    riskScore: 30,
    riskLevel: "LOW",
    createdAt: "2026-10-01T09:34:00",
    recommendedAction: "New customer, low COD amount. Send WhatsApp confirmation.",
  },
  // ---------- CONFIRMED ----------
  {
    id: "ord_1038",
    orderNumber: "#1038",
    customerId: "cus_001",
    customerName: "Ayesha Khan",
    customerPhone: "0301-2345678",
    city: "Lahore",
    address: "House 23, Block C, Gulberg III, Lahore",
    items: [
      { id: "i6", productId: "p6", title: "Embroidered Bed Sheet Set (Double)", sku: "BED-EMB-DBL", quantity: 1, unitPrice: 5400, totalPrice: 5400 },
    ],
    codAmount: 5400,
    shippingFee: 250,
    totalAmount: 5400,
    isCod: true,
    status: "CONFIRMED",
    riskScore: 25,
    riskLevel: "LOW",
    confirmationMethod: "CALL",
    confirmedAt: "2026-09-30T16:22:00",
    createdAt: "2026-09-30T15:10:00",
  },
  {
    id: "ord_1039",
    orderNumber: "#1039",
    customerId: "cus_005",
    customerName: "Usman Raza",
    customerPhone: "0300-5566778",
    city: "Faisalabad",
    address: "House 156, Peoples Colony No. 2, Faisalabad",
    items: [
      { id: "i7", productId: "p7", title: "Men's Formal Watch (Stainless Steel)", sku: "MEN-WAT-STL", quantity: 1, unitPrice: 8900, totalPrice: 8900 },
      { id: "i8", productId: "p8", title: "Leather Wallet", sku: "LTH-WLT-BRN", quantity: 1, unitPrice: 1600, totalPrice: 1600 },
    ],
    codAmount: 10500,
    shippingFee: 280,
    totalAmount: 10500,
    isCod: true,
    status: "CONFIRMED",
    riskScore: 18,
    riskLevel: "LOW",
    confirmationMethod: "WHATSAPP",
    confirmedAt: "2026-09-30T17:45:00",
    createdAt: "2026-09-30T17:12:00",
  },
  {
    id: "ord_1040",
    orderNumber: "#1040",
    customerId: "cus_007",
    customerName: "Fatima Noor",
    customerPhone: "0322-3344556",
    city: "Peshawar",
    address: "University Town, Peshawar",
    items: [
      { id: "i9", productId: "p9", title: "Hijab Cap Set (Pack of 3)", sku: "HJB-CAP-3PK", quantity: 1, unitPrice: 1450, totalPrice: 1450 },
    ],
    codAmount: 1450,
    shippingFee: 200,
    totalAmount: 1450,
    isCod: true,
    status: "CONFIRMED",
    riskScore: 12,
    riskLevel: "LOW",
    confirmationMethod: "WHATSAPP",
    confirmedAt: "2026-09-30T18:30:00",
    createdAt: "2026-09-30T18:05:00",
  },
  // ---------- IN TRANSIT ----------
  {
    id: "ord_1031",
    orderNumber: "#1031",
    customerId: "cus_002",
    customerName: "Bilal Ahmed",
    customerPhone: "0321-9876543",
    city: "Karachi",
    address: "Flat 4B, Al-Habib Apartments, Tariq Road, Karachi",
    items: [
      { id: "i10", productId: "p2", title: "Men's Casual Kameez Shalwar", sku: "MEN-CS-WHT", quantity: 1, unitPrice: 2400, totalPrice: 2400 },
    ],
    codAmount: 2400,
    shippingFee: 150,
    totalAmount: 2400,
    isCod: true,
    status: "IN_TRANSIT",
    riskScore: 8,
    riskLevel: "LOW",
    courier: "TCS",
    trackingNumber: "TCS-78451236",
    confirmedAt: "2026-09-29T14:20:00",
    createdAt: "2026-09-29T13:45:00",
    shipment: {
      id: "shp_1031",
      trackingNumber: "TCS-78451236",
      courier: "TCS",
      status: "IN_TRANSIT",
      shippingCost: 180,
      codAmount: 2400,
      shippedAt: "2026-09-30T09:00:00",
      events: [
        { id: "e1", status: "Order Confirmed", description: "Customer confirmed via WhatsApp", eventTime: "2026-09-29T14:20:00", source: "SHIPOPS" },
        { id: "e2", status: "Shipment Created", description: "Shipment booked with TCS", eventTime: "2026-09-30T08:45:00", source: "SHIPOPS" },
        { id: "e3", status: "Picked Up", description: "Package picked up from warehouse", location: "Lahore Sort Hub", eventTime: "2026-09-30T09:00:00", source: "COURIER" },
        { id: "e4", status: "In Transit", description: "Departed from Lahore Sorting Center", location: "Lahore", eventTime: "2026-09-30T14:30:00", source: "COURIER" },
        { id: "e5", status: "In Transit", description: "Arrived at Karachi Distribution Hub", location: "Karachi", eventTime: "2026-10-01T06:15:00", source: "COURIER" },
      ],
    },
  },
  {
    id: "ord_1032",
    orderNumber: "#1032",
    customerId: "cus_008",
    customerName: "Kamran Sheikh",
    customerPhone: "0346-7788990",
    city: "Karachi",
    address: "Bungalow 89, DHA Phase 6, Karachi",
    items: [
      { id: "i11", productId: "p10", title: "Smartphone (6GB RAM, 128GB)", sku: "SPH-6128-BLK", quantity: 1, unitPrice: 38900, totalPrice: 38900 },
    ],
    codAmount: 38900,
    shippingFee: 350,
    totalAmount: 38900,
    isCod: true,
    status: "OUT_FOR_DELIVERY",
    riskScore: 5,
    riskLevel: "LOW",
    courier: "LEOPARDS",
    trackingNumber: "LEO-5521789",
    confirmedAt: "2026-09-29T11:00:00",
    createdAt: "2026-09-29T10:30:00",
    shipment: {
      id: "shp_1032",
      trackingNumber: "LEO-5521789",
      courier: "LEOPARDS",
      status: "OUT_FOR_DELIVERY",
      shippingCost: 320,
      codAmount: 38900,
      shippedAt: "2026-09-30T10:00:00",
      events: [
        { id: "e6", status: "Order Confirmed", description: "Customer confirmed via call", eventTime: "2026-09-29T11:00:00", source: "SHIPOPS" },
        { id: "e7", status: "Picked Up", description: "Package picked up", location: "Lahore", eventTime: "2026-09-30T10:00:00", source: "COURIER" },
        { id: "e8", status: "In Transit", description: "Arrived at Karachi Hub", location: "Karachi", eventTime: "2026-10-01T04:00:00", source: "COURIER" },
        { id: "e9", status: "Out for Delivery", description: "Out for delivery with rider Imran K.", location: "Karachi — DHA", eventTime: "2026-10-01T09:30:00", source: "COURIER" },
      ],
    },
  },
  // ---------- NEEDS ATTENTION ----------
  {
    id: "ord_1025",
    orderNumber: "#1025",
    customerId: "cus_004",
    customerName: "Hira Saleem",
    customerPhone: "0345-1122334",
    city: "Islamabad",
    address: "Plot 12, Street 9, F-8/3, Islamabad",
    items: [
      { id: "i12", productId: "p11", title: "Designer Handbag (Faux Leather)", sku: "DSG-HB-BLK", quantity: 1, unitPrice: 8900, totalPrice: 8900 },
    ],
    codAmount: 8900,
    shippingFee: 300,
    totalAmount: 8900,
    isCod: true,
    status: "ATTENTION",
    riskScore: 45,
    riskLevel: "MEDIUM",
    courier: "TCS",
    trackingNumber: "TCS-78419987",
    attentionType: "BAD_ADDRESS",
    attentionReason: "Courier cannot find the house",
    attentionOverdueHours: 24,
    attentionAttemptsLeft: 2,
    confirmedAt: "2026-09-28T13:00:00",
    createdAt: "2026-09-28T12:15:00",
    recommendedAction: "Customer address incomplete — send WhatsApp message asking to confirm exact house/street number. Courier held the package for 1 more attempt.",
    shipment: {
      id: "shp_1025",
      trackingNumber: "TCS-78419987",
      courier: "TCS",
      status: "ATTENTION",
      shippingCost: 280,
      codAmount: 8900,
      shippedAt: "2026-09-29T09:00:00",
      events: [
        { id: "e10", status: "Out for Delivery", description: "Out for delivery", eventTime: "2026-09-30T10:00:00", source: "COURIER" },
        { id: "e11", status: "Delivery Attempt Failed", description: "Rider could not locate address. Reason: incomplete address.", eventTime: "2026-09-30T14:30:00", source: "COURIER", isWarning: true },
        { id: "e12", status: "AI Recommendation", description: "ShipOps AI flagged as BAD_ADDRESS. Recommended WhatsApp confirmation.", eventTime: "2026-09-30T14:31:00", source: "AI" },
      ],
    },
  },
  {
    id: "ord_1026",
    orderNumber: "#1026",
    customerId: "cus_005",
    customerName: "Usman Raza",
    customerPhone: "0300-5566778",
    city: "Faisalabad",
    address: "House 156, Peoples Colony No. 2, Faisalabad",
    items: [
      { id: "i13", productId: "p12", title: "Bluetooth Earbuds (Pro)", sku: "BT-EARB-PRO", quantity: 1, unitPrice: 5400, totalPrice: 5400 },
    ],
    codAmount: 5400,
    shippingFee: 220,
    totalAmount: 5400,
    isCod: true,
    status: "ATTENTION",
    riskScore: 18,
    riskLevel: "LOW",
    courier: "TRAX",
    trackingNumber: "TRX-9981234",
    attentionType: "CUSTOMER_UNREACHABLE",
    attentionReason: "Rider marked not available",
    attentionOverdueHours: 19,
    attentionAttemptsLeft: 3,
    confirmedAt: "2026-09-29T15:00:00",
    createdAt: "2026-09-29T14:30:00",
    recommendedAction: "Customer unavailable at delivery. Send WhatsApp asking for preferred delivery time window. Rider will retry tomorrow.",
  },
  {
    id: "ord_1027",
    orderNumber: "#1027",
    customerId: "cus_006",
    customerName: "Maham Ali",
    customerPhone: "0312-8899001",
    city: "Rawalpindi",
    address: "Flat 7, Saddar Plaza, Saddar, Rawalpindi",
    items: [
      { id: "i14", productId: "p13", title: "Perfume Set (3 x 50ml)", sku: "PRF-SET-3PK", quantity: 1, unitPrice: 5400, totalPrice: 5400 },
    ],
    codAmount: 5400,
    shippingFee: 240,
    totalAmount: 5400,
    isCod: true,
    status: "ATTENTION",
    riskScore: 68,
    riskLevel: "HIGH",
    courier: "M&P",
    trackingNumber: "MNP-4456789",
    attentionType: "CUSTOMER_REFUSED",
    attentionReason: "Courier says customer refused to accept",
    attentionOverdueHours: 19,
    attentionAttemptsLeft: 1,
    confirmedAt: "2026-09-29T10:00:00",
    createdAt: "2026-09-29T09:30:00",
    recommendedAction: "Customer refused at door, but WhatsApp conversation shows they confirmed earlier. Send recovery message: 'Rider says you refused — was there an issue?'. This is a high-risk RTO pattern.",
  },
  // ---------- DELIVERED ----------
  {
    id: "ord_1015",
    orderNumber: "#1015",
    customerId: "cus_005",
    customerName: "Usman Raza",
    customerPhone: "0300-5566778",
    city: "Faisalabad",
    address: "House 156, Peoples Colony No. 2, Faisalabad",
    items: [
      { id: "i15", productId: "p14", title: "Men's Wallet & Belt Combo", sku: "MEN-WLT-BLT", quantity: 1, unitPrice: 3200, totalPrice: 3200 },
    ],
    codAmount: 3200,
    shippingFee: 180,
    totalAmount: 3200,
    isCod: true,
    status: "DELIVERED",
    riskScore: 18,
    riskLevel: "LOW",
    courier: "TCS",
    trackingNumber: "TCS-78401122",
    confirmedAt: "2026-09-27T11:00:00",
    createdAt: "2026-09-27T10:30:00",
  },
  // ---------- RETURNING / RETURNED (RTO) ----------
  {
    id: "ord_1053",
    orderNumber: "#1053",
    customerId: "cus_003",
    customerName: "Sana Tariq",
    customerPhone: "0333-4567890",
    city: "Multan",
    address: "Street 7, Cantt, Multan",
    items: [
      { id: "i16", productId: "p15", title: "Home Decor Set (4 items)", sku: "HOM-DEC-4PK", quantity: 1, unitPrice: 4200, totalPrice: 4200 },
    ],
    codAmount: 4200,
    shippingFee: 240,
    totalAmount: 4200,
    isCod: true,
    status: "RETURNING",
    riskScore: 72,
    riskLevel: "HIGH",
    courier: "POSTEX",
    trackingNumber: "PFX-2200145",
    returnReason: "Refused to accept",
    confirmedAt: "2026-09-26T12:00:00",
    createdAt: "2026-09-26T11:30:00",
    recommendedAction: "RTO in progress. Customer WhatsApp reply contradicts courier ('Rider aaya hi nahi'). Escalate to courier dispute — evidence collected below.",
    evidence: [
      { id: "ev1", type: "COURIER_EVENT", title: "Out for delivery", detail: "Courier dispatched rider for delivery", timestamp: "2026-09-30T09:01:00", source: "PostEx" },
      { id: "ev2", type: "COURIER_EVENT", title: "Receiver refused to accept", detail: "Courier event code RD (Refused Delivery). Rider reported customer refused at door.", timestamp: "2026-09-30T14:01:00", source: "PostEx" },
      { id: "ev3", type: "WHATSAPP", title: "ShipOps Automation messaged customer", detail: "Auto-sent recovery message: 'We noticed a delivery issue with your order #1053. Was there a problem?'", timestamp: "2026-09-30T15:40:00", source: "ShipOps Automation" },
      { id: "ev4", type: "CUSTOMER_REPLY", title: "Customer replied on WhatsApp", detail: '"Rider aaya hi nahi. Main ghar par thi pura din."', timestamp: "2026-09-30T15:44:00", source: "Customer" },
      { id: "ev5", type: "AGENT_ACTION", title: "Dispute case opened", detail: "Operator marked as COURIER_DISPUTE. Evidence bundle prepared for courier claim.", timestamp: "2026-09-30T16:12:00", source: "Agent: Ayesha (Ops)" },
    ],
    shipment: {
      id: "shp_1053",
      trackingNumber: "PFX-2200145",
      courier: "POSTEX",
      status: "RETURNING",
      shippingCost: 240,
      codAmount: 4200,
      shippedAt: "2026-09-28T09:00:00",
      events: [
        { id: "ev_e1", status: "Picked Up", description: "Package picked up", eventTime: "2026-09-28T09:00:00", source: "COURIER" },
        { id: "ev_e2", status: "Out for Delivery", description: "Out for delivery", eventTime: "2026-09-30T09:01:00", source: "COURIER" },
        { id: "ev_e3", status: "Delivery Refused", description: "Receiver refused to accept. Code RD.", eventTime: "2026-09-30T14:01:00", source: "COURIER", isWarning: true },
        { id: "ev_e4", status: "Return Initiated", description: "Package on its way back to origin", eventTime: "2026-09-30T16:30:00", source: "COURIER", isWarning: true },
      ],
    },
  },
  {
    id: "ord_1048",
    orderNumber: "#1048",
    customerId: "cus_006",
    customerName: "Maham Ali",
    customerPhone: "0312-8899001",
    city: "Rawalpindi",
    address: "Flat 7, Saddar Plaza, Saddar, Rawalpindi",
    items: [
      { id: "i17", productId: "p16", title: "Hair Care Combo (Shampoo + Conditioner)", sku: "HCR-COM-2PK", quantity: 1, unitPrice: 2800, totalPrice: 2800 },
    ],
    codAmount: 2800,
    shippingFee: 200,
    totalAmount: 2800,
    isCod: true,
    status: "RETURNED",
    riskScore: 68,
    riskLevel: "HIGH",
    courier: "CALL_COURIER",
    trackingNumber: "CALL-6650123",
    returnReason: "Customer not available (3 attempts)",
    confirmedAt: "2026-09-22T14:00:00",
    createdAt: "2026-09-22T13:30:00",
    evidence: [
      { id: "ev6", type: "COURIER_EVENT", title: "Attempt 1 — Customer unavailable", detail: "Rider visited at 11:30 AM. Door locked.", timestamp: "2026-09-25T11:30:00", source: "Call Courier" },
      { id: "ev7", type: "WHATSAPP", title: "ShipOps sent reminder", detail: "Auto-reminder: 'Your order is out for delivery tomorrow. Please be available.'", timestamp: "2026-09-25T18:00:00", source: "ShipOps" },
      { id: "ev8", type: "COURIER_EVENT", title: "Attempt 2 — Customer unavailable", detail: "Rider visited at 4:15 PM. No response.", timestamp: "2026-09-26T16:15:00", source: "Call Courier" },
      { id: "ev9", type: "COURIER_EVENT", title: "Attempt 3 — Final attempt failed", detail: "Customer did not respond to calls or door.", timestamp: "2026-09-27T12:00:00", source: "Call Courier" },
      { id: "ev10", type: "AGENT_ACTION", title: "Return processed", detail: "RTO finalized. Stock return pending.", timestamp: "2026-09-28T10:00:00", source: "Agent: Bilal" },
    ],
  },
];

// ============================================================
// ATTENTION CASES (derived view)
// ============================================================
export const attentionCases: AttentionCase[] = [
  {
    id: "case_001",
    orderId: "ord_1025",
    orderNumber: "#1025",
    customerName: "Hira Saleem",
    city: "Islamabad",
    type: "BAD_ADDRESS",
    title: "Bad Address",
    description: "Courier cannot find the house. Address missing plot/house number.",
    priority: "HIGH",
    status: "OPEN",
    overdueHours: 24,
    attemptsLeft: 2,
    recommendedAction: "Send WhatsApp message asking customer to confirm exact house/street number. Courier will hold for 1 more attempt.",
    aiConfidence: 92,
    createdAt: "2026-09-30T14:31:00",
  },
  {
    id: "case_002",
    orderId: "ord_1026",
    orderNumber: "#1026",
    customerName: "Usman Raza",
    city: "Faisalabad",
    type: "CUSTOMER_UNREACHABLE",
    title: "Consignee Not Available",
    description: "Rider marked customer not available at delivery. 3 attempts left.",
    priority: "MEDIUM",
    status: "OPEN",
    overdueHours: 19,
    attemptsLeft: 3,
    recommendedAction: "Send WhatsApp asking for preferred delivery time window. Schedule retry for tomorrow.",
    aiConfidence: 87,
    createdAt: "2026-09-30T15:00:00",
  },
  {
    id: "case_003",
    orderId: "ord_1027",
    orderNumber: "#1027",
    customerName: "Maham Ali",
    city: "Rawalpindi",
    type: "CUSTOMER_REFUSED",
    title: "Refused to Accept",
    description: "Courier says customer refused. But WhatsApp shows earlier confirmation. Possible courier dispute.",
    priority: "URGENT",
    status: "OPEN",
    overdueHours: 19,
    attemptsLeft: 1,
    recommendedAction: "Send recovery message immediately. High RTO risk. Collect evidence for courier dispute.",
    aiConfidence: 95,
    createdAt: "2026-09-30T15:02:00",
  },
  {
    id: "case_004",
    orderId: "ord_1042",
    orderNumber: "#1042",
    customerName: "Asad Mahmood",
    city: "Lahore",
    type: "COURIER_DELAY",
    title: "Courier Delay",
    description: "Shipment stuck at sort hub for 36 hours. No movement.",
    priority: "MEDIUM",
    status: "IN_PROGRESS",
    overdueHours: 36,
    recommendedAction: "Contact TCS support. Consider re-dispatching via Leopards if no movement in 12h.",
    aiConfidence: 78,
    createdAt: "2026-09-29T08:00:00",
  },
  {
    id: "case_005",
    orderId: "ord_1041",
    orderNumber: "#1041",
    customerName: "Nida Yousuf",
    city: "Karachi",
    type: "DUPLICATE_ORDER",
    title: "Possible Duplicate Order",
    description: "Same customer placed 2 identical orders within 4 minutes. Likely accidental.",
    priority: "LOW",
    status: "OPEN",
    overdueHours: 5,
    recommendedAction: "Contact customer to confirm if both orders are intended. Cancel duplicate if not.",
    aiConfidence: 91,
    createdAt: "2026-10-01T07:00:00",
  },
];

// ============================================================
// WHATSAPP CONVERSATIONS
// ============================================================
export const whatsappConversations: WhatsAppConversation[] = [
  {
    id: "wa_001",
    customerId: "cus_003",
    customerName: "Sana Tariq",
    customerPhone: "0333-4567890",
    orderNumber: "#1053",
    lastMessage: "Rider aaya hi nahi. Main ghar par thi pura din.",
    lastMessageTime: "2026-09-30T15:44:00",
    unread: 1,
    status: "AWAITING_REPLY",
    messages: [
      { id: "m1", direction: "OUTBOUND", body: "Assalam o Alaikum Sana! Aap ka order #1053 (Home Decor Set) confirm karne ke liye, please reply CONFIRM ya CANCEL.", timestamp: "2026-09-26T12:30:00", status: "READ", isAutomated: true },
      { id: "m2", direction: "INBOUND", body: "CONFIRM", timestamp: "2026-09-26T12:45:00", status: "READ" },
      { id: "m3", direction: "OUTBOUND", body: "Shukriya! Aap ka order confirm ho gaya hai. Tracking number: PFX-2200145. Delivery 2-3 working days mein hogi.", timestamp: "2026-09-26T12:46:00", status: "READ", isAutomated: true },
      { id: "m4", direction: "OUTBOUND", body: "Aap ka order aaj delivery ke liye out ho gaya hai. Rider 11 AM - 5 PM ke darmiyan aayega.", timestamp: "2026-09-30T09:15:00", status: "READ", isAutomated: true },
      { id: "m5", direction: "OUTBOUND", body: "We noticed a delivery issue with your order #1053. Rider report ke mutabiq aap ne refused kiya. Kya masla tha?", timestamp: "2026-09-30T15:40:00", status: "READ", isAutomated: true },
      { id: "m6", direction: "INBOUND", body: "Rider aaya hi nahi. Main ghar par thi pura din.", timestamp: "2026-09-30T15:44:00", status: "DELIVERED" },
    ],
  },
  {
    id: "wa_002",
    customerId: "cus_002",
    customerName: "Bilal Ahmed",
    customerPhone: "0321-9876543",
    orderNumber: "#1044",
    lastMessage: "CONFIRM",
    lastMessageTime: "2026-10-01T08:55:00",
    unread: 0,
    status: "CONFIRMED",
    messages: [
      { id: "m7", direction: "OUTBOUND", body: "Assalam o Alaikum Bilal! Aap ka order #1044 (Men's Casual Kameez Shalwar x2 + Leather Sandals) COD Rs 6,200. Confirm karne ke liye reply CONFIRM ya CANCEL.", timestamp: "2026-10-01T08:47:00", status: "READ", isAutomated: true },
      { id: "m8", direction: "INBOUND", body: "CONFIRM", timestamp: "2026-10-01T08:55:00", status: "READ" },
    ],
  },
  {
    id: "wa_003",
    customerId: "cus_001",
    customerName: "Ayesha Khan",
    customerPhone: "0301-2345678",
    orderNumber: "#1043",
    lastMessage: "Please confirm — order #1043 Rs 4,500 COD",
    lastMessageTime: "2026-10-01T08:24:00",
    unread: 0,
    status: "AWAITING_REPLY",
    messages: [
      { id: "m9", direction: "OUTBOUND", body: "Assalam o Alaikum Ayesha! Aap ka order #1043 (Cotton Unstitched Suit 3 Piece) COD Rs 4,500. Confirm karne ke liye reply CONFIRM ya CANCEL.", timestamp: "2026-10-01T08:24:00", status: "DELIVERED", isAutomated: true },
    ],
  },
  {
    id: "wa_004",
    customerId: "cus_006",
    customerName: "Maham Ali",
    customerPhone: "0312-8899001",
    orderNumber: "#1027",
    lastMessage: "Ok I will check and let you know",
    lastMessageTime: "2026-09-30T16:20:00",
    unread: 2,
    status: "AWAITING_REPLY",
    messages: [
      { id: "m10", direction: "OUTBOUND", body: "Maham, rider ke mutabiq aap ne order #1027 refuse kiya. Kya koi masla tha? Hum aap ki help kar sakte hain.", timestamp: "2026-09-30T16:00:00", status: "READ", isAutomated: true },
      { id: "m11", direction: "INBOUND", body: "Ok I will check and let you know", timestamp: "2026-09-30T16:20:00", status: "DELIVERED" },
    ],
  },
  {
    id: "wa_005",
    customerId: "cus_004",
    customerName: "Hira Saleem",
    customerPhone: "0345-1122334",
    orderNumber: "#1025",
    lastMessage: "House 23, Street 9, F-8/3 — ghar ke bahar blue gate hai",
    lastMessageTime: "2026-10-01T07:45:00",
    unread: 1,
    status: "RESOLVED",
    messages: [
      { id: "m12", direction: "OUTBOUND", body: "Hira, rider aap ka ghar nahi dhund saka. Address complete share karein (house number, street, landmark).", timestamp: "2026-10-01T07:30:00", status: "READ", isAutomated: true },
      { id: "m13", direction: "INBOUND", body: "House 23, Street 9, F-8/3 — ghar ke bahar blue gate hai", timestamp: "2026-10-01T07:45:00", status: "DELIVERED" },
    ],
  },
];

// ============================================================
// COURIER INTEGRATIONS
// ============================================================
export const courierIntegrations: CourierIntegration[] = [
  {
    id: "cr_001",
    provider: "TCS",
    displayName: "TCS",
    accountName: "Main Account",
    accountNumber: "TC-784512",
    status: "CONNECTED",
    connectedAt: "2026-03-15",
    shipmentsCount: 1684,
    deliveryRate: 92.5,
    avgCost: 220,
    logoColor: "#E63946",
    description: "Pakistan's largest courier network. Best for major cities and high-value COD.",
  },
  {
    id: "cr_002",
    provider: "LEOPARDS",
    displayName: "Leopards Courier",
    accountName: "Primary",
    accountNumber: "LP-552178",
    status: "CONNECTED",
    connectedAt: "2026-03-15",
    shipmentsCount: 1120,
    deliveryRate: 89.6,
    avgCost: 198,
    logoColor: "#F4A261",
    description: "Wide coverage including remote areas. Competitive rates for bulk dispatch.",
  },
  {
    id: "cr_003",
    provider: "TRAX",
    displayName: "Trax Online",
    accountName: "Default",
    accountNumber: "TR-998123",
    status: "CONNECTED",
    connectedAt: "2026-04-02",
    shipmentsCount: 542,
    deliveryRate: 90.5,
    avgCost: 175,
    logoColor: "#2A9D8F",
    description: "Fast COD remittance cycle (T+3). Good for cash flow sensitive operations.",
  },
  {
    id: "cr_004",
    provider: "M&P",
    displayName: "M&P Courier",
    accountName: "Main",
    accountNumber: "MP-445678",
    status: "CONNECTED",
    connectedAt: "2026-05-18",
    shipmentsCount: 388,
    deliveryRate: 88.6,
    avgCost: 185,
    logoColor: "#6A4C93",
    description: "Strong in Punjab region. Same-day pickup in Lahore.",
  },
  {
    id: "cr_005",
    provider: "POSTEX",
    displayName: "PostEx",
    accountName: "Default",
    accountNumber: "PX-220014",
    status: "CONNECTED",
    connectedAt: "2026-06-10",
    shipmentsCount: 296,
    deliveryRate: 86.1,
    avgCost: 168,
    logoColor: "#1D3557",
    description: "Digital-first courier with real-time API. Fast remittance (T+1).",
  },
  {
    id: "cr_006",
    provider: "CALL_COURIER",
    displayName: "Call Courier",
    accountName: "Main",
    accountNumber: "CC-665012",
    status: "CONNECTED",
    connectedAt: "2026-07-01",
    shipmentsCount: 184,
    deliveryRate: 87.3,
    avgCost: 160,
    logoColor: "#457B9D",
    description: "Cost-effective for small parcels. Nationwide coverage.",
  },
  {
    id: "cr_007",
    provider: "RIDER",
    displayName: "Rider (Local)",
    accountName: "Karachi Only",
    status: "DISCONNECTED",
    shipmentsCount: 0,
    deliveryRate: 0,
    avgCost: 120,
    logoColor: "#8D99AE",
    description: "Same-day delivery within Karachi. Setup required for local dispatch.",
  },
];

// ============================================================
// AUTOMATION RULES
// ============================================================
export const automationRules: AutomationRule[] = [
  {
    id: "auto_001",
    name: "COD WhatsApp Confirmation",
    description: "Send WhatsApp confirmation request when a new COD order arrives from Shopify.",
    trigger: "ORDER_CREATED",
    triggerLabel: "Order Created",
    conditions: ["Payment method = COD", "Order status = UNCONFIRMED"],
    actions: ["Send WhatsApp template 'order_confirm'", "Schedule reminder #1 after 30 min"],
    enabled: true,
    runsLast30Days: 1842,
    successRate: 94.2,
    lastRunAt: "2026-10-01T08:47:00",
  },
  {
    id: "auto_002",
    name: "Confirmation Reminder #1",
    description: "If no customer reply in 30 minutes, send first reminder.",
    trigger: "ORDER_PENDING_30MIN",
    triggerLabel: "No reply 30 min",
    conditions: ["Order status = UNCONFIRMED", "No customer reply in 30 min"],
    actions: ["Send WhatsApp reminder #1"],
    enabled: true,
    runsLast30Days: 612,
    successRate: 38.4,
    lastRunAt: "2026-10-01T08:30:00",
  },
  {
    id: "auto_003",
    name: "Confirmation Reminder #2",
    description: "If still no reply after 4 hours, send second reminder.",
    trigger: "ORDER_PENDING_4H",
    triggerLabel: "No reply 4 hours",
    conditions: ["Order status = UNCONFIRMED", "No customer reply in 4 hours"],
    actions: ["Send WhatsApp reminder #2", "Flag for manual call review"],
    enabled: true,
    runsLast30Days: 248,
    successRate: 21.7,
    lastRunAt: "2026-10-01T06:00:00",
  },
  {
    id: "auto_004",
    name: "Auto-Confirm on Customer Reply",
    description: "When customer replies CONFIRM, automatically move order to Confirmed stage.",
    trigger: "CUSTOMER_MESSAGE_RECEIVED",
    triggerLabel: "Customer replied",
    conditions: ["Message body matches 'CONFIRM'", "Order status = UNCONFIRMED"],
    actions: ["Set order status = CONFIRMED", "Notify operator", "Trigger 'Create Shipment' suggestion"],
    enabled: true,
    runsLast30Days: 1248,
    successRate: 99.6,
    lastRunAt: "2026-10-01T08:55:00",
  },
  {
    id: "auto_005",
    name: "Auto-Cancel on CANCEL Reply",
    description: "When customer replies CANCEL, cancel the order and notify merchant.",
    trigger: "CUSTOMER_MESSAGE_RECEIVED",
    triggerLabel: "Customer replied",
    conditions: ["Message body matches 'CANCEL'", "Order status = UNCONFIRMED"],
    actions: ["Set order status = CANCELLED", "Notify operator", "Log reason"],
    enabled: true,
    runsLast30Days: 184,
    successRate: 100,
    lastRunAt: "2026-10-01T07:12:00",
  },
  {
    id: "auto_006",
    name: "AI Risk Check on High-Value COD",
    description: "Run AI risk analysis on COD orders above Rs 10,000 before dispatch.",
    trigger: "ORDER_CONFIRMED",
    triggerLabel: "Order confirmed",
    conditions: ["COD amount >= 10,000", "Customer risk score > 50 OR new customer"],
    actions: ["Run AI risk analysis", "Flag for manual review if HIGH risk", "Hold shipment creation"],
    enabled: true,
    runsLast30Days: 92,
    successRate: 100,
    lastRunAt: "2026-09-30T17:45:00",
  },
  {
    id: "auto_007",
    name: "Needs Attention Auto-Triage",
    description: "When courier reports an exception, create Attention case with AI classification.",
    trigger: "DELIVERY_FAILED",
    triggerLabel: "Delivery failed",
    conditions: ["Courier event = failed/exception"],
    actions: ["Create Attention case", "Run AI classification", "Send recovery WhatsApp to customer"],
    enabled: true,
    runsLast30Days: 78,
    successRate: 96.1,
    lastRunAt: "2026-09-30T14:31:00",
  },
  {
    id: "auto_008",
    name: "Out-for-Delivery Customer Alert",
    description: "Notify customer on WhatsApp when shipment is out for delivery.",
    trigger: "SHIPMENT_OUT_FOR_DELIVERY",
    triggerLabel: "Out for delivery",
    conditions: ["Shipment status = OUT_FOR_DELIVERY"],
    actions: ["Send WhatsApp 'out_for_delivery' template"],
    enabled: true,
    runsLast30Days: 1684,
    successRate: 99.2,
    lastRunAt: "2026-10-01T09:30:00",
  },
  {
    id: "auto_009",
    name: "Delivered — Request Review",
    description: "24 hours after delivery, send WhatsApp review request.",
    trigger: "ORDER_DELIVERED_24H",
    triggerLabel: "Delivered +24h",
    conditions: ["Order status = DELIVERED", "24 hours since delivery"],
    actions: ["Send WhatsApp review request", "Apply discount coupon if low rating"],
    enabled: false,
    runsLast30Days: 0,
    successRate: 0,
  },
  {
    id: "auto_010",
    name: "RTO Evidence Bundle",
    description: "When RTO initiated, automatically collect all evidence into a single bundle for dispute.",
    trigger: "RETURN_CREATED",
    triggerLabel: "Return initiated",
    conditions: ["Return status = initiated"],
    actions: ["Compile evidence timeline", "Generate dispute PDF", "Notify ops team"],
    enabled: true,
    runsLast30Days: 24,
    successRate: 100,
    lastRunAt: "2026-09-30T16:12:00",
  },
];

// ============================================================
// TEAM MEMBERS
// ============================================================
export const teamMembers: TeamMember[] = [
  { id: "u1", name: "Hamza Sheikh", email: "hamza@demostore.pk", role: "OWNER", status: "ACTIVE", lastActiveAt: "2026-10-01T09:15:00", avatarColor: "#0F766E" },
  { id: "u2", name: "Ayesha Tariq", email: "ayesha.ops@demostore.pk", role: "ADMIN", status: "ACTIVE", lastActiveAt: "2026-10-01T09:02:00", avatarColor: "#C2410C" },
  { id: "u3", name: "Bilal Khan", email: "bilal@demostore.pk", role: "MANAGER", status: "ACTIVE", lastActiveAt: "2026-09-30T18:40:00", avatarColor: "#6A4C93" },
  { id: "u4", name: "Sana Malik", email: "sana@demostore.pk", role: "OPERATOR", status: "ACTIVE", lastActiveAt: "2026-10-01T08:55:00", avatarColor: "#1D3557" },
  { id: "u5", name: "Usman Ali", email: "usman@demostore.pk", role: "OPERATOR", status: "ACTIVE", lastActiveAt: "2026-09-30T20:12:00", avatarColor: "#2A9D8F" },
  { id: "u6", name: "Nida Yousuf", email: "nida@demostore.pk", role: "VIEWER", status: "INVITED", lastActiveAt: "", avatarColor: "#8D99AE" },
];

// AI Insights (daily summary)
export const aiInsights = {
  dailySummary: {
    date: "2026-10-01",
    totalOrders: 84,
    confirmed: 41,
    pendingConfirmation: 23,
    attentionCases: 5,
    rtoPredicted: 7,
    revenueAtRisk: 38400,
  },
  predictions: [
    {
      id: "pred_1",
      orderId: "#1045",
      customerName: "Sana Tariq",
      riskScore: 78,
      riskLevel: "HIGH" as const,
      prediction: "78% probability of RTO based on customer history (4 prior returns) and incomplete address.",
      recommendedAction: "Verify by phone call before dispatch. Offer advance payment option.",
      impact: "Rs 3,800 + Rs 220 shipping at risk",
    },
    {
      id: "pred_2",
      orderId: "#1027",
      customerName: "Maham Ali",
      riskScore: 85,
      riskLevel: "HIGH" as const,
      prediction: "Courier reports refusal but customer WhatsApp suggests rider never arrived. Likely false refusal — dispute recommended.",
      recommendedAction: "Escalate to M&P courier with evidence bundle. Hold RTO processing.",
      impact: "Rs 5,400 + courier dispute",
    },
    {
      id: "pred_3",
      orderId: "#1041",
      customerName: "Nida Yousuf",
      riskScore: 62,
      riskLevel: "MEDIUM" as const,
      prediction: "Duplicate order detected within 4 minutes. Likely accidental double-checkout.",
      recommendedAction: "Contact customer to confirm intent. Cancel duplicate if unintended.",
      impact: "Rs 4,200 potential refund",
    },
    {
      id: "pred_4",
      orderId: "#1038",
      customerName: "Ayesha Khan",
      riskScore: 15,
      riskLevel: "LOW" as const,
      prediction: "Reliable customer (9/12 delivered). Auto-confirm recommended.",
      recommendedAction: "No action needed. Proceed to shipment creation.",
      impact: "Rs 5,400 expected revenue",
    },
  ],
  automationsSuggested: [
    { id: "sug_1", title: "Add auto-SMS fallback for unresponsive WhatsApp", reason: "12% of unconfirmed orders never reply on WhatsApp but respond to SMS within 1 hour.", impact: "~18 additional confirmations / month" },
    { id: "sug_2", title: "Block orders from repeat RTO customers", reason: "3 customers have >50% RTO rate. Auto-flagging could save Rs 18,000/month in courier costs.", impact: "Rs 18,000 / month savings" },
    { id: "sug_3", title: "Switch Faisalabad orders from TCS to Trax", reason: "Trax shows 94% delivery rate in Faisalabad vs TCS 88%. Same cost.", impact: "~6 fewer RTOs / month" },
  ],
};
